<?php

return [
	'teams' => [
		'Arizona Diamondbacks' => 'ARI',
		'Atlanta Braves' => 'ATL',
		'Baltimore Orioles' => 'BAL',
		'Boston Red Sox' => 'BOS',
		'Chicago Cubs' => 'CHC',
		'Chicago White Sox' => 'CHW',
		'Cincinnati Reds' => 'CIN',
		'Cleveland Indians' => 'CLE',
		'Colorado Rockies' => 'COL',
		'Detroit Tigers' => 'DET',
		'Houston Astros' => 'HOU',
		'Kansas City Royals' => 'KCR',
		'Los Angeles Angels' => 'ANA',
		'Los Angeles Dodgers' => 'LAD',
		'Miami Marlins' => 'FLA',
		'Milwaukee Brewers' => 'MIL',
		'Minnesota Twins' => 'MIN',
		'New York Mets' => 'NYM',
		'New York Yankees' => 'NYY',
		'Oakland Athletics' => 'OAK',
		'Philadelphia Phillies' => 'PHI',
		'Pittsburgh Pirates' => 'PIT',
		'San Diego Padres' => 'SDP',
		'San Francisco Giants' => 'SFG',
		'Seattle Mariners' => 'SEA',
		'St. Louis Cardinals' => 'STL',
		'Tampa Bay Rays' => 'TBD',
		'Texas Rangers' => 'TEX',
		'Toronto Blue Jays' => 'TOR',
		'Washington Nationals' => 'WSN',
	],
];